---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - dnsmasq
      - nfs-kernel-server
    state: present

- name: Base folder should exist
  ansible.builtin.file:
    path: "{{ pipxe_base_dir }}/"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Setup tftproot
  ansible.builtin.file:
    path: "{{ pipxe_base_dir }}/tftproot"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Dnsmasq config
  ansible.builtin.template:
    src: templates/dnsmasq-pxe.config.j2
    dest: /etc/dnsmasq.d/pipxe.config
    owner: root
    group: root
    mode: "0622"
  notify:
    - Restart dnsmasq

- name: Dnsmasq enabled an started
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true

- name: Nfs exports directory
  ansible.builtin.file:
    dest: /etc/exports.d/
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Setup indivual hosts
  include_tasks: host-setup.yaml
  loop: "{{ pipxe_hosts }}"
  loop_control:
    loop_var: host
