- hosts: containers
  roles:
    - role: nspawn-container
      vars:
        hostname: "{{inventory_hostname}}"
    - role: auto-upgrade

- hosts: pihole
  roles:
    - role: pihole
  vars:
    pihole_web_password: "{{lookup('community.general.onepassword', 'pihole', vault='nas', field='password')}}"
    pihole_dns_1: 10.143.174.1
