---
- name: Setup static ips
  hosts:
    - grafana
    - pihole
  roles:
    - static-ip

- name: Basic setup for nspawn containsers
  hosts: containers
  roles:
    - role: nspawn-container
      vars:
        hostname: "{{ inventory_hostname }}"
    - role: auto-upgrade
    - role: exim4_mail_relay

- name: Setup pihole container
  hosts: pihole
  roles:
    - role: pihole

- name: Setup grafana container
  hosts: grafana
  roles:
    - prometheus.prometheus.prometheus
    - prometheus.prometheus.alertmanager
    - grafana.grafana.grafana
