dlna_server_directories:
    - path: /nas/ssd/share/MP3/Alben/
      type: A

fs_hosts_allow: 10.143.174.0/24
fs_workgroup: LAN
fs_shares:
  - name: nas-ssd
    public: true
    path: /nas/ssd/share
  - name: backup
    public: true
    path: /backup/share
