- hosts: nas_host
  become: true
  vars_files:
    - ./nas-settings.yaml
  roles:
    - role: nftables
    - role: bridge
      vars:
        ifname: priv-net
        dhcp:
          range_start: 192.168.1.100
          range_end: 192.168.1.254
        ipv4:
          address: 192.168.1.1/24
    - role: auto-upgrade
    - role: dlna-server
    - role: file-server
    - role: pi-pxe-boot
    - role: offsite-backup
    - role: nspawn-host
