- hosts: nas_host
  become: true
  vars_files:
    - ./nas-settings.yaml
  roles:
    - role: auto-upgrade
    - role: dlna-server
    - role: file-server
    - role: pi-pxe-boot
    - role: offsite-backup
    - role: nspawn-host
