---
- name: Setup nas
  hosts: nas
  become: true
  roles:
    - role: nftables
    - role: bridge
    - role: exim4_mail_relay
    - role: auto-upgrade
    - role: dlna-server
    - role: file-server
    - role: pi-pxe-boot
    - role: offsite-backup
    - role: nspawn-host
    - role: container-proxy
    - role: node_exporter
    - role: debian_backports
      vars:
        # contrib is require for zfs
        debian_backports_archives: main contrib

  handlers:

  tasks:
    - name: Install ZFS
      ansible.builtin.package:
        name:
          - linux-headers-amd64
          - zfsutils-linux
          - zfs-dkms
      tags: ['zfs']
