---
collections:
  - name: ansible.posix
  - name: containers.podman
  - name: community.general
    version: ">=8.5.0"
  - name: community.libvirt
  - name: grafana.grafana
  - name: prometheus.prometheus
