- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ cert_item.domains | first | replace('*.', '') }}/cert.pem
  register: _certbot_dns_letsencrypt_cert

- name: Generate new certificate if one doesn't exist.
  command: >-
    certbot certonly
        {% if certbot_dns_test %}--test-cert{% endif %}
        --dns-cloudflare
        --dns-cloudflare-credentials {{ certbot_dns_cloudflare_credentials }}
    --noninteractive --agree-tos
    --email {{ certbot_dns_email }}
    -d {{ cert_item.domains | join(',') }}
  when: not _certbot_dns_letsencrypt_cert.stat.exists
