---
# we are already root when connecting via machinectl and sudo is not installed
ansible_become: false

systemd_networkd: false

static_ip:
  ifname: host0
  ipv4:
    address: 192.168.1.10/24
    gateway: 192.168.1.1

prometheus_web_external_url: /prometheus
prometheus_scrape_configs:
  - job_name: "fritz-exporter"
    scrape_interval: 50s
    scrape_timeout: 45s
    static_configs:
      - targets:
          - 192.168.1.20:9787
  - job_name: "node-file-servicediscovery"
    file_sd_configs:
      - files:
        # reference to prometheus_targets.node
          - "{{ prometheus_config_dir }}/file_sd/node.yml"

prometheus_targets:
  node:
    - targets:
        - 192.168.1.1:9100
        - pi01:9100

prometheus_alert_rules_files:
  - "inventory/grafana/prometheus/rules/*.rules"
prometheus_alertmanager_config:
  - path_prefix: /alertmanager/
    static_configs:
      - targets:
          - localhost:9093

alertmanager_web_external_url: http://localhost/alertmanager
alertmanager_smtp:
  from: 'grafana@wollawurst.info'
  smarthost: 'localhost:25'
  require_tls: false
alertmanager_receivers:
  - name: 'null'
  - name: 'email'
    email_configs:
      - to: 'root@localhost'
        send_resolved: true
alertmanager_route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 24h
  receiver: 'email'
  routes:
    - match:
        # we want to ignore the watchdog alert, it could be used to
        # build a dead man switch that triggers an alert if this
        # alert stops firing.
        alertname: Watchdog
      receiver: "null"

grafana_url: http://0.0.0.0/grafana/
grafana_security:
  admin_user: "{{ lookup('community.general.onepassword', 'grafana admin', vault='nas', field='username') }}"
  admin_password: "{{ lookup('community.general.onepassword', 'grafana admin', vault='nas', field='password') }}"
# Workaround for grafana 11: https://github.com/grafana/grafana-ansible-collection/issues/220
grafana_alerting: {}
grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090/prometheus/
    basicAuth: false
    jsonData:
      timeInterval: 15s
