---
auto_upgrades_additional_origins_pattern:
  # the 1password repo has some strange meta data
  - o=. stable,a=stable
  - o=${distro_id} Backports,n=${distro_codename}-backports

nftables_nat_rules:
  postrouting:
    - iifname priv-net masquerade
nftables_nat_ip6_rules:
  postrouting:
    - iifname priv-net masquerade
  prerouting:
    - udp dport 53 dnat to fd00::5:53

zfs_pools:
  - name: ssd-pool1
    members: >-
      mirror
      /dev/disk/by-id/wwn-0x500a0751e5de6bfa
      /dev/disk/by-id/wwn-0x500a0751e9887e7b
zfs_volumes:
  - name: ssd-pool1/ssd
    extra_zfs_properties:
      compression: 'lz4'
      acltype: 'posix'
  - name: ssd-pool1/backup
    extra_zfs_properties:
      compression: 'lz4'
      acltype: 'posix'

bridge_bridges:
  - ifname: priv-net
    dhcp:
      range_start: 192.168.1.100
      range_end: 192.168.1.254
    ipv4:
      address: 192.168.1.1/24
    ipv6:
      address: fd00::1/64

exim4_mail_relay_additional_interfaces:
  - 192.168.1.1
exim4_mail_relay_nets:
  - 192.168.1.1/24

dlna_server_directories:
  - path: /ssd-pool1/ssd/share/MP3/Alben/
    type: A

fs_hosts_allow: 10.143.174.0/24
fs_workgroup: LAN
fs_shares:
  - name: nas-ssd
    public: true
    path: /ssd-pool1/ssd/share
  - name: backup
    public: true
    path: /ssd-pool1/backup/share

pipxe_interface: eth0
# dnsmasq dhcp range that will be proxies to the other dhcp server
pipxe_dhcp_range: 10.143.174.255
pipxe_base_dir: /ssd-pool1/ssd/pipxe
pipxe_bootstrap_img: .cache/pi.img
pipxe_hosts:
  - name: retropi
    # old kernel
    nfsvers: 3
    mac: b8:27:eb:95:ec:6e
    serial: 6e95ec6e

offline_backup_paths:
  - /ssd-pool1/ssd/share/
  - /ssd-pool1/backup/
offline_backup_devices:
  - uuid: b3e45358-6df5-49bd-a0e7-6ad89be08d37
    name: seagate-4tb

ob_backend_base_url: "{{ lookup('community.general.onepassword', 'offsitebackup', vault='nas', field='base-url') }}"
ob_before_backup: |
  source ~/.config/env.local.sh
ob_passphrase: op://nas/nas-backup-passphrase/passphrase
ob_locations:
  - src: /ssd-pool1/ssd/pipxe/
  - src: /ssd-pool1/backup/
  - name: ssd-share
    src: /ssd-pool1/ssd/share
  - name: container-pihole-config
    src: /var/lib/machines/pihole/etc/pihole
  - name: container-grafana-config
    src: /var/lib/machines/grafana/var/lib/grafana/

nas_bind_mount_machines_folder: /ssd-pool1/ssd/systemd-machines
nh_containers:
  - name: pihole
    os: debian
    ports:
      - udp:53:53
    bridge: priv-net
  - name: grafana
    os: debian
    bridge: priv-net
  - name: fritz-exporter
    os: debian
    bridge: priv-net

cloudflare_dns_records:
  - zone: "{{ public_dns_zone_name }}"
    record: nas
    type: A
    value: "{{ ansible_facts['default_ipv4']['address'] }}"

certbot_dns_cloudflare_api_token: "{{ cloudflare_dns_api_token }}"
certbot_dns_email: "{{ lookup('community.general.onepassword', 'letsencrypt email', vault='nas', field='email') }}"
certbot_dns_certs:
  - domains:
      - nas.{{ public_dns_zone_name }}
certbot_dns_post_hooks:
  - "systemctl reload nginx"

container_proxy_ssl: true
container_proxy_ssl_host: "nas.{{ public_dns_zone_name }}"
container_proxy_ssl_cert: "/etc/letsencrypt/live/{{ container_proxy_ssl_host | replace('*.', '') }}/fullchain.pem"
container_proxy_ssl_key: "/etc/letsencrypt/live/{{ container_proxy_ssl_host | replace('*.', '') }}/privkey.pem"
container_proxy_routes:
  - title: Grafana
    path: /grafana
    backend: http://192.168.1.10:3000/
    type: grafana
    icon: https://upload.wikimedia.org/wikipedia/commons/a/a1/Grafana_logo.svg
  - title: Prometheus
    path: /prometheus
    # no trailing / otherwise redirect loop
    backend: http://192.168.1.10:9090
    icon: https://upload.wikimedia.org/wikipedia/commons/3/38/Prometheus_software_logo.svg
  - title: Alertmanager
    path: /alertmanager
    backend: http://192.168.1.10:9093
    icon: https://upload.wikimedia.org/wikipedia/commons/3/38/Prometheus_software_logo.svg
  - title: Pi-hole
    path: /pihole/admin
    backend: http://192.168.1.5/admin/
    type: pihole
    icon: https://upload.wikimedia.org/wikipedia/en/1/15/Pi-hole_vector_logo.svg

node_exporter_listen_address: 192.168.1.1:9100
# this is already the default config on debian
# node_exporter_textfile_collector_dir: /var/lib/prometheus/node-exporter/
