---
auto_upgrade_additional_origins_pattern:
  # the 1password repo has some strange meta data
  - o=. stable,a=stable

nftables_nat_rules:
  - iifname priv-net masquerade


bridge_bridges:
  - ifname: priv-net
    dhcp:
      range_start: 192.168.1.100
      range_end: 192.168.1.254
    ipv4:
      address: 192.168.1.1/24

exim4_mail_relay_additional_interfaces:
  - 192.168.1.1
exim4_mail_relay_nets:
  - 192.168.1.1/24

dlna_server_directories:
  - path: /nas/ssd/share/MP3/Alben/
    type: A

fs_hosts_allow: 10.143.174.0/24
fs_workgroup: LAN
fs_shares:
  - name: nas-ssd
    public: true
    path: /nas/ssd/share
  - name: backup
    public: true
    path: /backup/share

pipxe_interface: eth0
# dnsmasq dhcp range that will be proxies to the other dhcp server
pipxe_dhcp_range: 10.143.174.255
pipxe_base_dir: /pipxe
pipxe_bootstrap_img: .cache/pi.img
pipxe_hosts:
  - name: retropi
    # old kernel
    nfsvers: 3
    mac: b8:27:eb:95:ec:6e
    serial: 6e95ec6e

ob_backend_base_url: boto3+s3://narkat-offsite-backups
ob_before_backup: |
  source ~/.config/env.local.sh
ob_aws:
  access_key_id: op://nas/aws-nas-user-access-key/aws_access_key_id
  secret_access_key: op://nas/aws-nas-user-access-key/aws_secret_access_key
ob_passphrase: op://nas/nas-backup-passphrase/passphrase
ob_locations:
  - src: /pipxe/
  - src: /backup/
  - name: ssd-share
    src: /nas/ssd/share
  - name: container-pihole-config
    src: /var/lib/machines/pihole/etc/pihole
  - name: container-grafana-config
    src: /var/lib/machines/grafana/var/lib/grafana/

nh_containers:
  - name: pihole
    os: debian
    ports:
      - udp:53:53
    bridge: priv-net
  - name: grafana
    os: debian
    bridge: priv-net

container_proxy_routes:
  - path: /grafana
    backend: http://192.168.1.10:3000/
    type: grafana
  - path: /prometheus
    # no trailing / otherwise redirect loop
    backend: http://192.168.1.10:9090
  - path: /alertmanager
    backend: http://192.168.1.10:9093
  - path: /pihole/
    backend: http://192.168.1.5/admin/
