---
all:
  hosts:
    nas:
      ansible_connection: local
    pi01:
      ansible_connection: ssh
    pihole:
      ansible_connection: machinectl
      ansible_host: pihole
    grafana:
      ansible_connection: machinectl
      ansible_host: grafana
    fritz-exporter:
      ansible_connection: machinectl
      ansible_host: fritz-exporter
  children:
    containers:
      hosts:
        pihole:
        grafana:
        fritz-exporter:
    internet_mail_relay:
      hosts:
        nas:
        pi01:
