---
all:
  hosts:
    nas:
      ansible_connection: local
    pihole:
      ansible_connection: machinectl
      ansible_host: pihole
    grafana:
      ansible_connection: machinectl
      ansible_host: grafana
  children:
    containers:
      hosts:
        pihole:
        grafana:
