---
- name: Enable systemd-networkd
  ansible.builtin.service:
    name: systemd-networkd
    enabled: true
    state: started
  when:
    - systemd_networkd is not defined or systemd_networkd

- name: Setup hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Setup hosts file
  ansible.builtin.template:
    dest: /etc/hosts
    src: hosts.j2
    owner: root
    group: root
    mode: "0644"
