- name: Enable systemd-networkd
  ansible.builtin.service:
    name: systemd-networkd
    enabled: true
    state: started
  when:
    - systemd_networkd is not defined or systemd_networkd

- name: Setup hostname
  ansible.builtin.hostname:
    name: "{{hostname}}"
