---
- name: Reload systemd for offline-backup
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Reload udev rules for offline-backup
  ansible.builtin.command:
    cmd: udevadm control --reload-rules
