- name: Install node exporter
  ansible.builtin.package:
    name: prometheus-node-exporter

- name: Configure node exporter
  ansible.builtin.template:
    dest: /etc/prometheus.conf
    src: templates/prometheus.conf.j2
  notify:
    - Restart node exporter

- name: Create override dir
  ansible.builtin.file:
    dest: /etc/systemd/system/prometheus-node-exporter.service.d/
    state: directory
    owner: root
    group: root
    mode: "0744"

- name: Settings override
  ansible.builtin.copy:
    dest: /etc/systemd/system/prometheus-node-exporter.service.d/override.conf
    content: |
      [Service]
      EnvironmentFile=/etc/prometheus.conf
  notify:
    - Restart node exporter

# The node-exporter depends on ipmitools -> openipmi which tries to
# start during boot and fails becuase there is not ipmi chip...
- name: Disable openipmi service
  ansible.builtin.service:
    name: openipmi
    enabled: false
