- name: Setup bridge config
  ansible.builtin.template:
    dest: /etc/network/interfaces.d/bridge-{{ bridge.ifname }}
    src: bridge-interface.j2
    owner: root
    group: root
    mode: "0644"
  register: bridge_config
  tags: bridge

- name: Shutdown interface
  ansible.builtin.command: ifdown {{ bridge.ifname }}
  when: bridge_config.changed
  tags: bridge

- name: Start interface
  ansible.builtin.command: ifup {{ bridge.ifname }}
  when: bridge_config.changed
  tags: bridge

- name: Disable DAD
  ansible.posix.sysctl:
    name: net.ipv6.conf.{{ bridge.ifname }}.accept_dad
    value: "0"
    state: present
    sysctl_file: /etc/sysctl.d/55-disable-dad-{{ bridge.ifname }}.conf
    reload: true
  when:
    - bridge.ipv6 is defined
    - not (bridge.ipv6.dad | default(true))
  tags: bridge

- name: Setup DHCP
  ansible.builtin.import_tasks: dhcp.yaml
  when: bridge.dhcp_server is defined
  tags: bridge
