---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - dnsmasq
    state: present
  tags: bridge

- name: Bridge config {{ bridge.ifname }}
  ansible.builtin.template:
    src: templates/dnsmasq-dhcp.config.j2
    dest: /etc/dnsmasq.d/bridge-{{ bridge.ifname }}.config
    owner: root
    group: root
    mode: "0622"
  notify:
    - Restart dnsmasq
  tags: bridge
