- name: Install dependencies
  ansible.builtin.package:
    name:
      - dnsmasq
    state: present

- name: Bridge {{ ifname }} dhcp config
  ansible.builtin.template:
    src: "templates/dnsmasq-dhcp.config.j2"
    dest: "/etc/dnsmasq.d/bridge-{{ ifname }}.config"
    owner: root
    group: root
    mode: "0622"
  notify:
    - restart dnsmasq
