---
# we need the if-pre-up.d bridge plugin this package supplies
- name: Install depenencies
  ansible.builtin.package:
    name: bridge-utils

- name: Setup interface.d include
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    line: source /etc/network/interfaces.d/*

- name: Create bridges
  ansible.builtin.include_tasks: "bridge.yaml"
  loop: "{{ bridge_bridges }}"
  loop_control:
    loop_var: bridge
