---
# The ifupdown bridge plugin is supplied by bridge-utils.
- name: Install dependencies
  ansible.builtin.package:
    name: bridge-utils
    state: present
  tags: bridge

- name: Validate bridge configuration
  ansible.builtin.assert:
    that:
      - bridge.type == 'isolated'
      - bridge.ipv4.method == 'static'
      - bridge.ipv4.address is defined
      - bridge.ipv6 is not defined or bridge.ipv6.method == 'static'
      - bridge.ipv6 is not defined or bridge.ipv6.address is defined
    fail_msg: >-
      Only isolated bridges with static addresses are supported currently.
  loop: "{{ bridge_bridges }}"
  loop_control:
    loop_var: bridge
    label: "{{ bridge.ifname }}"
  tags: bridge

- name: Setup interface.d include
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    line: source /etc/network/interfaces.d/*
  tags: bridge

- name: Enable routing
  ansible.builtin.template:
    src: templates/sysctl-ip-forwarding.conf.j2
    dest: /etc/sysctl.d/50-ip-forwarding.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload sysctl
  tags: bridge

- name: Create bridges
  ansible.builtin.include_tasks: "bridge.yaml"
  loop: "{{ bridge_bridges }}"
  loop_control:
    loop_var: bridge
  tags: bridge
