---
- name: Validate firewall configuration
  ansible.builtin.assert:
    that:
      - nftables_config.input.policy in ['accept', 'drop']
      - nftables_config.input.presets | difference(nftables_presets.keys()) | length == 0
    fail_msg: >-
      Invalid input policy or unknown nftables preset. Available presets:
      {{ nftables_presets.keys() | list | sort | join(', ') }}
  tags: nftables

- name: Install nftables
  ansible.builtin.package:
    name: nftables
    state: present
  tags: nftables

- name: Create directories
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
  tags: nftables
  loop:
    - /etc/nftables.d
    - /etc/nftables.d/tables

- name: Configure NAT rules
  ansible.builtin.template:
    dest: /etc/nftables.d/tables/nat.conf
    src: nat.conf.j2
    owner: root
    group: root
    mode: "0644"
    validate: nft -cf %s
  notify: Reload nftables
  tags: nftables

- name: Create nftables config file
  ansible.builtin.template:
    dest: /etc/nftables.conf
    src: nftables.conf.j2
    owner: root
    group: root
    mode: "0644"
    validate: nft -cf %s
  notify: Reload nftables
  tags: nftables

- name: Enable nftables ruleset loading
  ansible.builtin.service:
    name: nftables
    enabled: true
    state: started
  tags: nftables
