#!/usr/bin/env bash

machine_name="$1"
if [[ ! "$machine_name" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?$ ]]; then
    echo "Error: Invalid hostname format. Use only letters, numbers, and hyphens. Cannot start/end with hyphen."
    exit 1
fi

sudo machinectl stop "$machine_name"
sudo rm "/etc/systemd/nspawn/$machine_name.nspawn"
sudo rm -rf "/var/lib/machines/$machine_name"
