---
- name: Install minidlna
  ansible.builtin.package:
    name: minidlna
    state: present

- name: Sysctl config for minidlna
  ansible.builtin.template:
    src: ../templates/sysctl.conf.j2
    dest: /etc/sysctl.d/50-local-minidlna.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  notify:
    - Apply sysctl

- name: Minidlna config
  ansible.builtin.template:
    src: ../templates/minidlna.conf.j2
    dest: /etc/minidlna.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  notify:
    - Restart minidlna
