---
- name: Converge isolated bridge
  hosts: all
  any_errors_fatal: true
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 0
      when: ansible_facts["pkg_mgr"] == "apt"
  roles:
    - role: "../../../bridge"
      vars:
        bridge_bridges:
          - ifname: priv-test
            type: isolated
            forwarding: true
            dhcp_server:
              range_start: 192.0.2.100
              range_end: 192.0.2.200
            ipv4:
              method: static
              address: 192.0.2.1/24
            ipv6:
              method: static
              address: fd00:ffff::1/64
              dad: false
