---
- name: Bootstrap container
  block:
    - name: "Bootstrap debian for {{ container.name }}"
      ansible.builtin.command: >-
        debootstrap --include=systemd,dbus,systemd-container,python3
          stable "/var/lib/machines/{{ container.name }}"
      args:
        creates: /var/lib/machines/{{ container.name }}
      tags: ['nspawn']

  rescue:
    - name: "Delete container folder afer failure {{ container.name }}"
      ansible.builtin.file:
        dest: /var/lib/machines/{{ container.name }}
        state: absent
      tags: ['nspawn']

- name: "Create nspawn file {{ container.name }}"
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0644"
    src: ../templates/container.nspawn.j2
    dest: /etc/systemd/nspawn/{{ container.name }}.nspawn
  register: config
  tags: ['nspawn']

- name: "Container should autostart and be started {{ container.name }}"
  ansible.builtin.service:
    name: systemd-nspawn@{{ container.name }}
    enabled: true
    state: started
  tags: ['nspawn']

- name: "Reboot container after config change {{ container.name }}"
  ansible.builtin.command: machinectl reboot "{{ container.name }}"
  when: config.changed
  tags: ['nspawn']
