name: test
on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@v7

      - name: Set up python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'

      - name: Test duplicity_prometheus.py
        run: ./roles/offsite-backup/templates/test_duplicity_prometheus.py

  molecule:
    name: Molecule tests
    uses: ./.github/workflows/molecule-discovery.yaml
