- name: Install Samba
  ansible.builtin.package:
    name: samba
    state: present

- name: Guest user
  ansible.builtin.user:
    name: nas
    group: nas
    create_home: false
    shell: /usr/sbin/nologin
    system: yes
  become: yes
  register: guest_user

- name: Samba config
  ansible.builtin.template:
    src: ../templates/smb.conf.j2
    dest: /etc/samba/smb.conf
    mode: '0644'
  become: true
  notify:
    - restart smbd

- name: Share permissions
  ansible.builtin.file:
    dest: "{{item.path}}"
    owner: "{{guest_user.name}}"
    group: "{{guest_user.group}}"
    mode: "0765"
  loop: "{{fs_shares}}"
  become: yes
