---
- name: Install git
  ansible.builtin.package:
    name:
      - git

- name: Clone pi-hole repo
  ansible.builtin.git:
    repo: https://github.com/pi-hole/pi-hole.git /etc/.pihole
    dest: /etc/.pihole
    depth: 1
    update: false

- name: Create pihole config dir
  ansible.builtin.file:
    dest: /etc/pihole
    mode: "0775"
    state: directory

- name: Install pi-hole
  ansible.builtin.command: "'/etc/.pihole/automated install/basic-install.sh' --unattended"
  args:
    creates: /opt/pihole
  register: pihole_install

- name: Set Pi-hole configuration settings
  ansible.builtin.command:
    cmd: "pihole-FTL --config {{ item.key }} '{{ item.value }}'"
  with_items:
    - { key: "dns.upstreams", value: "{{ [pihole_dns_1, pihole_dns_2, pihole_dns_3, pihole_dns_4]
        | select('defined')
        | select('string')
        | to_json
        }}"
    }
    - { key: "webserver.paths.prefix", value: "/pihole" }
  register: pihole_config

- name: Set Pi-hole Web password
  ansible.builtin.command:
    cmd: "pihole-FTL --config webserver.api.password '{{ pihole_web_password }}'"
  no_log: true
